/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350.pne;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    Map<String, Integer> wordMap = new Map<String, Integer>();
}
