/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350.pne;

public class App {

    public static void main(String[] args) {
        Map<String, Integer> wordMap 
            =documentMap(args);
    }
}
